version: '3.8'

services:
  postgres:
    container_name: room-finder-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: roomscout
      POSTGRES_PASSWORD: roomscout
      POSTGRES_DB: roomscoutdb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
