@baseUrl= http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Bob User",
    "email":"bobuser@mail.com",
    "password":"123456",
    "role":"user"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email":"bobuser@mail.com",
    "password":"123456"
}

###

# @name add_balance
POST {{baseUrl}}/balance
Content-Type: application/json
Authorization: Bearer {{authToken}}